# Generated by Django 2.1.4 on 2018-12-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menus',
            options={'verbose_name_plural': 'menus'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'orders'},
        ),
        migrations.AddField(
            model_name='menus',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
