# Generated by Django 2.1.4 on 2018-12-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181219_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='coffee_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
